apiVersion: batch/v1
kind: Job
metadata:
  name: db-upate
spec:
  template:
    metadata:
      name: db-update
    spec:
      restartPolicy: Never
      backoffLimit: 1
      containers:
      - name: rails
        image: us.gcr.io/counting-company-production/rails
        envFrom:
          - secretRef:
              name: rails-environment
        volumeMounts:
          - name: cloudstorage-instance-credentials
            mountPath: /secrets
            readOnly: true
        command: ["rake",  "db:migrate", "db:seed"]
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.09
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=counting-company-production:us-east1:counting-company-production=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssl/certs
          - name: cloudsql
            mountPath: /cloudsql
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: cloudstorage-instance-credentials
          secret:
            secretName: cloudstorage-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
