apiVersion: batch/v1
kind: Job
metadata:
  name: rake
spec:
  template:
    metadata:
      name: rake
    spec:
      restartPolicy: Never
      containers:
      - name: rails
        image: us.gcr.io/counting-company-production/rails
        envFrom:
          - secretRef:
              name: rails-environment
        volumeMounts:
          - name: cloudstorage-instance-credentials
            mountPath: /secrets
            readOnly: true
        command: ["rake"]
        args: $$RAKECMD
      volumes:
        - name: cloudstorage-instance-credentials
          secret:
            secretName: cloudstorage-instance-credentials
