# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ml.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "PredictorRequest" do
    optional :image, :bytes, 1
  end
  add_message "PredictorReply" do
    optional :version, :string, 1
    optional :density_map, :bytes, 2
    optional :crowd_count, :float, 3
    optional :line_count, :float, 4
  end
end

PredictorRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("PredictorRequest").msgclass
PredictorReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("PredictorReply").msgclass
