# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: protos/ml.proto for package ''

require 'grpc'
require 'protos/ml_pb'

module CrowdCount
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'CrowdCount'

    rpc :Predict, PredictorRequest, PredictorReply
  end

  Stub = Service.rpc_stub_class
end
