# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "CountRequest" do
    optional :image, :bytes, 1
  end
  add_message "CountReply" do
    optional :version, :string, 1
    optional :density_map, :bytes, 2
    optional :crowd_count, :float, 3
    optional :line_count, :float, 4
  end
end

CountRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("CountRequest").msgclass
CountReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("CountReply").msgclass
