# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "CountCrowdRequest" do
    optional :image, :bytes, 1
  end
  add_message "CountCrowdReply" do
    optional :version, :string, 1
    optional :density_map, :bytes, 2
    optional :crowd_count, :float, 3
    optional :line_count, :float, 4
  end
end

CountCrowdRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("CountCrowdRequest").msgclass
CountCrowdReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("CountCrowdReply").msgclass
