# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: ml.proto for package ''

require 'grpc'
require_relative './ml_pb'

module RPC
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'RPC'

    rpc :CountCrowd, CountRequest, CountReply
    rpc :CountLine, CountRequest, CountReply
  end

  Stub = Service.rpc_stub_class
end
