apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: cloudsqlproxy
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: cloudsqlproxy
  template:
    metadata:
      labels:
        app: cloudsqlproxy
    spec:
      containers:
        # https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/Kubernetes.md
        - image: gcr.io/cloudsql-docker/gce-proxy:1.10
          name: cloudsqlproxy
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=counting-company-production:us-east1:counting-company-production=tcp:0.0.0.0:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          ports:
          - containerPort: 5432
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: cloudsql
              mountPath: /cloudsql
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: cloudsql
          emptyDir:
