apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dbtostorage
spec:
  schedule: "3 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          backoffLimit: 2
          containers:
          - name: rails
            image: us.gcr.io/counting-company-production/rails
            envFrom:
              - secretRef:
                  name: rails-environment
            command: ["rake"]
            args: ["db:dump_gcs"]
