apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: prediction-shakecam
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          #backoffLimit: 1
          containers:
          - name: rails
            image: us.gcr.io/counting-company-production/rails
            envFrom:
              - secretRef:
                  name: rails-environment
            command: ["rake"]
            args: ["prediction:shakecam"]
