development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: counting-company-development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: cable-production
