apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rails-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
        - name: rails
          image: us.gcr.io/counting-company-production/rails
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: rails-environment
