source 'https://rubygems.org'
ruby '~> 2.4.1'
#ruby-gemset=counting_company

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'active_model_serializers'
gem 'american_date'
gem 'arel'
gem 'auto_strip_attributes'
gem 'bootstrap', '~> 4.0.0.beta'
gem 'bootstrap4-kaminari-views'
gem 'bugsnag'
gem 'coffee-rails' # Only here for sprockets beta
gem 'datafix', :github => 'dimroc/datafix'
gem 'devise'
gem 'draper'
gem 'env_guard', github: 'dimroc/env_guard'
gem 'external_id', github: 'dimroc/external_id'
gem 'font-awesome-rails'
gem 'friendly_id'
gem 'google-cloud-storage', github: 'dimroc/google-cloud-ruby'
gem 'grpc'
gem 'image_processing'
gem 'imgix-rails'
gem 'jquery-rails'
gem 'kaminari'
gem 'mini_magick'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.7'
gem 'pundit'
gem 'pycall'
gem 'rails'
gem 'redis', '~> 3.3'  # Temporary fix until ActionCable gets patched
gem 'sass-rails', '~> 5.0'
gem 'slim-rails'
gem 'shrine'
gem 'shrine-google_cloud_storage', github: 'dimroc/shrine-google_cloud_storage'
gem 'sprockets', '4.0.0beta5'
gem 'turbolinks', '~> 5'
gem 'uglifier', '>= 1.3.0'
gem 'webpacker', github: 'rails/webpacker'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'foreman'
  gem 'fuubar'
  gem 'jshint', github: 'dimroc/jshint'
  gem 'pry'
  gem 'pry-byebug'
  gem 'rspec-rails'
  gem 'webmock'
end

group :development do
  gem 'bullet'
  gem 'grpc-tools'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

group :test do
  gem 'shrine-memory'
end
